name: wemovies_mobile_test
description: "Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  collection: ^1.18.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/errorcart.png
   - assets/finish.png
   - assets/refresh.png
   - assets/splash.png

flutter_native_splash:
  color: "#2F2E41"
  image: assets/splash.png
  android_12:
    color: "#2F2E41"
    image: assets/splash.png
